minify slugid.py
taskcluster/slugid.py pull request #14
Opened 2021-10-14 06:33 UTC by milahu

before: 55 lines
after: 24 lines

2021-10-22 21:32 UTC, jwhitlock requested changes
Thanks for the PR @milahu, and sorry it took me a week to review. We don't have CI hooked up, so I need to run the tests locally.

There's one failing test, and I think the ``nice()`` algorithm should do the same bit manipulation of other slugid versions, like the main [javascript version](https://github.com/taskcluster/slugid/blob/ce3bf62c6c50b7da014ce568e4510944d306d6f0/slugid.js#L74-L82).

I think the docstrings are useful and should be retained.

Why are you interested in reducing the length of this module? It is not something I usually work to optimize.

2021-10-22 21:32 UTC, jwhitlock commented on slugid/slugid.py
> -    """
The docstrings are important, and shouldn't be removed

2021-10-22 21:32 UTC, jwhitlock commented on slugid/slugid.py
> +    return _ascii(base64.urlsafe_b64encode(uuid_.bytes)[:-2])
The changes `decode('utf-8')` to `decode('ascii')`. I think this is still safe since `urlsafe_b64encode` explicitly emits ASCII-safe bytes, so ✓

2021-10-22 21:32 UTC, jwhitlock commented on slugid/slugid.py
> -    """
Again, keep docstrings

2021-10-22 21:32 UTC, jwhitlock commented on slugid/slugid.py
> -    """
Keep this docstring

2021-10-22 21:32 UTC, jwhitlock commented on slugid/slugid.py
> +    return encode(uuid.uuid4())
This works for me on Python 2.7 and 3.9 ✓

2021-10-22 21:32 UTC, jwhitlock commented on slugid/slugid.py
> +      s[0] = 'f'
This fails for me with:

```
TypeError: 'str' object does not support item assignment
```

Your version will be different than other implementations of slugid, because this `nice()` returns slugs starting with a digit. I'd prefer this in sync with the other versions and use the same technique.

2021-10-22 21:32 UTC, jwhitlock commented on slugid/slugid.py
> -    """
One more docstring to keep

2021-10-23 07:17 UTC, milahu commented
> I think the docstrings are useful and should be retained.
>
> Why are you interested in reducing the length of this module? It is not something I usually work to optimize.

code should be self-explanatory (intuitive), so these verbose docstrings are a "code smell" to me

verbose docstrings suggest that something terribly complex is going on,
but slugid is just a trivial wrapper around the uuid function

i would reduce it to one docstring for the whole module, showing the "sample use" of slugid

```py
slug = slugid.nice()
# slug == "abcdefgh...."

id = uuid.uuid()
slug = slugid.encode(id)
# slug == "abcdefgh...."
```

nitpick: encode is the wrong term, cos its a lossy transformation ...

> the nice() algorithm should do the same bit manipulation of other slugid versions

again, this is unnecessarily obscure (micro optimization, runs faster, harder to read)
but i agree:

> I'd prefer this in sync with the other versions and use the same technique.

2022-01-13 15:58 UTC, jwhitlock commented
I think there are some useful things here, but we're not going to agree on dropping docstrings, changing algorithms between implementations, or using non-black formatting. Also, this project needs to run tests on PRs.

2022-01-13 15:58 UTC, closed without merging